### ISSUE TITLE
validation pipeline failure:  error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by bluebrown** [s3-actions/s3cmd#10]
https://github.com/s3-actions/s3cmd/actions/runs/5012491798/jobs/8984500833

```
ncc: Version 0.28.0
ncc: Compiling file index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at hashOf (/home/runner/work/s3cmd/s3cmd/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:3[25](https://github.com/s3-actions/s3cmd/actions/runs/5012491798/jobs/8984500833#step:3:26)3136)
    at ncc (/home/runner/work/s3cmd/s3cmd/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:3257334)
    at runCmd (/home/runner/work/s3cmd/s3cmd/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:51539)
    at 819 (/home/runner/work/s3cmd/s3cmd/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:48346)
    at __webpack_require__ (/home/runner/work/s3cmd/s3cmd/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55045)
    at /home/runner/work/s3cmd/s3cmd/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55196
    at /home/runner/work/s3cmd/s3cmd/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55222
    at Object.<anonymous> (/home/runner/work/s3cmd/s3cmd/node_modules/@vercel/ncc/dist/ncc/cli.js:8:[28](https://github.com/s3-actions/s3cmd/actions/runs/5012491798/jobs/8984500833#step:3:29)) {
  opensslErrorStack: [ 'error:0[30](https://github.com/s3-actions/s3cmd/actions/runs/5012491798/jobs/8984500833#step:3:31)00086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by bluebrown** [comment]
fix through https://github.com/s3-actions/s3cmd/commit/92bac66a5df8e35458ddbd7dd3424b70cd828197
